# Generated by Django 5.0.6 on 2024-07-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_examlog_additional_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examlog',
            options={'verbose_name_plural': 'Exam Logs'},
        ),
    ]
