# Generated by Django 5.0.6 on 2024-07-13 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlog',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
